import axios from 'axios';

const API_BASE_URL = 'http://localhost:5000/api/v1';

export const api = axios.create({
  baseURL: API_BASE_URL,
  withCredentials: true,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Initial mock data with 30 realistic employee records (25 comprehensive HR fields each)
export const MOCK_EMPLOYEES = [
  {
    id: 1,
    employee_id: 'EMP-1001',
    name: 'Alex Morgan',
    email: 'alex.morgan@company.com',
    phone: '+1 (555) 234-5678',
    department: 'Engineering',
    role: 'Senior Frontend Developer',
    status: 'Active',
    joining_date: '2022-03-15',
    salary: '$115,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    // 10 Additional Enterprise HR Fields
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '6 Years',
    emergency_contact: '+1 (555) 987-6543 (Spouse)',
    dob: '1993-05-24',
    gender: 'Female',
    skills: 'React, TypeScript, Tailwind, GraphQL',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-4821',
    bank_account_last4: 'ACC-****-8842',
  },
  {
    id: 2,
    employee_id: 'EMP-1002',
    name: 'David Chen',
    email: 'david.chen@company.com',
    phone: '+1 (555) 876-5432',
    department: 'Product',
    role: 'Lead UX Designer',
    status: 'Active',
    joining_date: '2021-08-01',
    salary: '$128,000',
    blood_group: 'A+',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'David Chen',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '8 Years',
    emergency_contact: '+1 (555) 876-1122 (Parent)',
    dob: '1990-11-12',
    gender: 'Male',
    skills: 'Figma, Design Systems, User Research, Prototyping',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-3190',
    bank_account_last4: 'ACC-****-5521',
  },
  {
    id: 3,
    employee_id: 'EMP-1003',
    name: 'Sophia Williams',
    email: 'sophia.w@company.com',
    phone: '+1 (555) 345-6789',
    department: 'Marketing',
    role: 'Growth Manager',
    status: 'On Leave',
    joining_date: '2023-01-10',
    salary: '$92,000',
    blood_group: 'B-',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    manager_name: 'Alex Morgan',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'London Office',
    employment_type: 'Full-Time',
    experience: '4 Years',
    emergency_contact: '+1 (555) 345-0099 (Sibling)',
    dob: '1995-08-30',
    gender: 'Female',
    skills: 'SEO, Performance Marketing, Analytics, Copywriting',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-9012',
    bank_account_last4: 'ACC-****-1234',
  },
  {
    id: 4,
    employee_id: 'EMP-1004',
    name: 'Marcus Vance',
    email: 'marcus.v@company.com',
    phone: '+1 (555) 901-2345',
    department: 'Engineering',
    role: 'Backend Architect',
    status: 'Active',
    joining_date: '2020-05-20',
    salary: '$140,000',
    blood_group: 'AB+',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Austin Tech Center',
    employment_type: 'Full-Time',
    experience: '10 Years',
    emergency_contact: '+1 (555) 901-7788 (Spouse)',
    dob: '1988-03-14',
    gender: 'Male',
    skills: 'Node.js, PostgreSQL, Microservices, Kubernetes, AWS',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-6743',
    bank_account_last4: 'ACC-****-9081',
  },
  {
    id: 5,
    employee_id: 'EMP-1005',
    name: 'Elena Rostova',
    email: 'elena.r@company.com',
    phone: '+1 (555) 456-7890',
    department: 'Human Resources',
    role: 'HR Business Partner',
    status: 'Active',
    joining_date: '2022-11-01',
    salary: '$88,000',
    blood_group: 'O-',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Elena Rostova',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '5 Years',
    emergency_contact: '+1 (555) 456-3322 (Spouse)',
    dob: '1994-09-18',
    gender: 'Female',
    skills: 'Talent Management, Employee Relations, HRIS, Compliance',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1154',
    bank_account_last4: 'ACC-****-4432',
  },
  {
    id: 6,
    employee_id: 'EMP-1006',
    name: 'James Taylor',
    email: 'james.t@company.com',
    phone: '+1 (555) 678-9012',
    department: 'Sales',
    role: 'Account Executive',
    status: 'Inactive',
    joining_date: '2021-04-12',
    salary: '$75,000',
    blood_group: 'A-',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    manager_name: 'Sophia Williams',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '3 Years',
    emergency_contact: '+1 (555) 678-4455 (Parent)',
    dob: '1996-01-22',
    gender: 'Male',
    skills: 'B2B Sales, CRM, Negotiation, Lead Generation',
    performance_rating: 'Needs Improvement',
    tax_id: 'SSN-****-7781',
    bank_account_last4: 'ACC-****-6671',
  },
  {
    id: 7,
    employee_id: 'EMP-1007',
    name: 'Emily Davis',
    email: 'emily.davis@company.com',
    phone: '+1 (555) 789-0123',
    department: 'Finance',
    role: 'Financial Analyst',
    status: 'Active',
    joining_date: '2022-06-18',
    salary: '$85,000',
    blood_group: 'B+',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '4 Years',
    emergency_contact: '+1 (555) 789-1133 (Spouse)',
    dob: '1995-12-04',
    gender: 'Female',
    skills: 'Financial Modeling, Excel, Budgeting, Forecasting',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-2245',
    bank_account_last4: 'ACC-****-3312',
  },
  {
    id: 8,
    employee_id: 'EMP-1008',
    name: 'Robert Miller',
    email: 'robert.m@company.com',
    phone: '+1 (555) 890-1234',
    department: 'Engineering',
    role: 'DevOps Engineer',
    status: 'Active',
    joining_date: '2021-11-05',
    salary: '$120,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    manager_name: 'Marcus Vance',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Seattle Tech Hub',
    employment_type: 'Full-Time',
    experience: '7 Years',
    emergency_contact: '+1 (555) 890-9988 (Spouse)',
    dob: '1991-04-16',
    gender: 'Male',
    skills: 'Docker, CI/CD, Terraform, AWS, Linux',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-9981',
    bank_account_last4: 'ACC-****-7762',
  },
  {
    id: 9,
    employee_id: 'EMP-1009',
    name: 'Jessica Wilson',
    email: 'jessica.w@company.com',
    phone: '+1 (555) 901-2345',
    department: 'Product',
    role: 'Product Manager',
    status: 'Active',
    joining_date: '2020-09-14',
    salary: '$135,000',
    blood_group: 'A+',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '9 Years',
    emergency_contact: '+1 (555) 901-4433 (Spouse)',
    dob: '1989-10-09',
    gender: 'Female',
    skills: 'Product Roadmap, Agile, Scrum, Market Analysis',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-4456',
    bank_account_last4: 'ACC-****-8812',
  },
  {
    id: 10,
    employee_id: 'EMP-1010',
    name: 'Michael Brown',
    email: 'michael.b@company.com',
    phone: '+1 (555) 012-3456',
    department: 'Marketing',
    role: 'SEO Specialist',
    status: 'Inactive',
    joining_date: '2023-03-22',
    salary: '$70,000',
    blood_group: 'AB-',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    manager_name: 'Sophia Williams',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Remote (Florida)',
    employment_type: 'Contract',
    experience: '2 Years',
    emergency_contact: '+1 (555) 012-7711 (Parent)',
    dob: '1997-06-30',
    gender: 'Male',
    skills: 'Google Analytics, Semrush, Keyword Research, On-Page SEO',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-1109',
    bank_account_last4: 'ACC-****-2234',
  },
  {
    id: 11,
    employee_id: 'EMP-1011',
    name: 'Samantha Clark',
    email: 'samantha.c@company.com',
    phone: '+1 (555) 123-4567',
    department: 'Human Resources',
    role: 'Recruiter',
    status: 'On Leave',
    joining_date: '2022-08-30',
    salary: '$78,000',
    blood_group: 'O-',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    manager_name: 'Elena Rostova',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '3 Years',
    emergency_contact: '+1 (555) 123-8877 (Spouse)',
    dob: '1996-02-14',
    gender: 'Female',
    skills: 'Technical Sourcing, LinkedIn Recruiter, Interviewing',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-5561',
    bank_account_last4: 'ACC-****-9901',
  },
  {
    id: 12,
    employee_id: 'EMP-1012',
    name: 'Daniel Martinez',
    email: 'daniel.m@company.com',
    phone: '+1 (555) 234-8901',
    department: 'Engineering',
    role: 'Full Stack Engineer',
    status: 'Active',
    joining_date: '2022-01-15',
    salary: '$110,000',
    blood_group: 'A+',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    manager_name: 'Marcus Vance',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Austin Tech Center',
    employment_type: 'Full-Time',
    experience: '5 Years',
    emergency_contact: '+1 (555) 234-9900 (Spouse)',
    dob: '1993-11-08',
    gender: 'Male',
    skills: 'Vue.js, Express, MongoDB, Tailwind',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-3321',
    bank_account_last4: 'ACC-****-4410',
  },
  {
    id: 13,
    employee_id: 'EMP-1013',
    name: 'Olivia Harris',
    email: 'olivia.h@company.com',
    phone: '+1 (555) 345-9012',
    department: 'Sales',
    role: 'Sales Director',
    status: 'Active',
    joining_date: '2019-11-01',
    salary: '$160,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '12 Years',
    emergency_contact: '+1 (555) 345-7766 (Spouse)',
    dob: '1986-07-25',
    gender: 'Female',
    skills: 'Enterprise Strategy, Revenue Growth, Team Leadership',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-8819',
    bank_account_last4: 'ACC-****-1192',
  },
  {
    id: 14,
    employee_id: 'EMP-1014',
    name: 'Ethan White',
    email: 'ethan.w@company.com',
    phone: '+1 (555) 456-0123',
    department: 'Finance',
    role: 'Senior Accountant',
    status: 'Active',
    joining_date: '2020-04-10',
    salary: '$95,000',
    blood_group: 'B+',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150',
    manager_name: 'Emily Davis',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '6 Years',
    emergency_contact: '+1 (555) 456-8811 (Spouse)',
    dob: '1992-09-02',
    gender: 'Male',
    skills: 'General Ledger, Auditing, Tax Filing, Quickbooks',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-4472',
    bank_account_last4: 'ACC-****-5581',
  },
  {
    id: 15,
    employee_id: 'EMP-1015',
    name: 'Chloe Anderson',
    email: 'chloe.a@company.com',
    phone: '+1 (555) 567-1234',
    department: 'Product',
    role: 'UI Designer',
    status: 'Active',
    joining_date: '2023-02-01',
    salary: '$88,000',
    blood_group: 'A-',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150',
    manager_name: 'David Chen',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '3 Years',
    emergency_contact: '+1 (555) 567-2244 (Parent)',
    dob: '1996-10-14',
    gender: 'Female',
    skills: 'Illustration, UI Components, Micro-interactions, Adobe XD',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-9921',
    bank_account_last4: 'ACC-****-3341',
  },
  {
    id: 16,
    employee_id: 'EMP-1016',
    name: 'Benjamin Thomas',
    email: 'benjamin.t@company.com',
    phone: '+1 (555) 678-2345',
    department: 'Engineering',
    role: 'QA Automation Lead',
    status: 'Active',
    joining_date: '2021-07-19',
    salary: '$105,000',
    blood_group: 'AB-',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150',
    manager_name: 'Marcus Vance',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Seattle Tech Hub',
    employment_type: 'Full-Time',
    experience: '7 Years',
    emergency_contact: '+1 (555) 678-6611 (Spouse)',
    dob: '1991-01-30',
    gender: 'Male',
    skills: 'Cypress, Playwright, Selenium, Jest, CI Testing',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-6632',
    bank_account_last4: 'ACC-****-7719',
  },
  {
    id: 17,
    employee_id: 'EMP-1017',
    name: 'Ava Jackson',
    email: 'ava.j@company.com',
    phone: '+1 (555) 789-3456',
    department: 'Marketing',
    role: 'Content Strategist',
    status: 'On Leave',
    joining_date: '2022-09-05',
    salary: '$82,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=150',
    manager_name: 'Sophia Williams',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Remote (Oregon)',
    employment_type: 'Part-Time',
    experience: '4 Years',
    emergency_contact: '+1 (555) 789-5500 (Spouse)',
    dob: '1994-06-19',
    gender: 'Female',
    skills: 'Content Planning, Blogging, Brand Voice, PR',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-1188',
    bank_account_last4: 'ACC-****-9920',
  },
  {
    id: 18,
    employee_id: 'EMP-1018',
    name: 'Lucas King',
    email: 'lucas.k@company.com',
    phone: '+1 (555) 890-4567',
    department: 'Sales',
    role: 'Business Development Specialist',
    status: 'Active',
    joining_date: '2023-05-12',
    salary: '$72,000',
    blood_group: 'B-',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    manager_name: 'Olivia Harris',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '2 Years',
    emergency_contact: '+1 (555) 890-3344 (Parent)',
    dob: '1998-02-11',
    gender: 'Male',
    skills: 'Cold Outreach, Salesforce, Lead Qualification',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-4411',
    bank_account_last4: 'ACC-****-8822',
  },
  {
    id: 19,
    employee_id: 'EMP-1019',
    name: 'Mia Wright',
    email: 'mia.w@company.com',
    phone: '+1 (555) 901-5678',
    department: 'Human Resources',
    role: 'Talent Acquisition Manager',
    status: 'Active',
    joining_date: '2020-10-08',
    salary: '$96,000',
    blood_group: 'A+',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150',
    manager_name: 'Elena Rostova',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '7 Years',
    emergency_contact: '+1 (555) 901-2299 (Spouse)',
    dob: '1991-08-17',
    gender: 'Female',
    skills: 'Executive Search, Employer Branding, Negotiations',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-7720',
    bank_account_last4: 'ACC-****-3301',
  },
  {
    id: 20,
    employee_id: 'EMP-1020',
    name: 'Alexander Scott',
    email: 'alexander.s@company.com',
    phone: '+1 (555) 012-6789',
    department: 'Engineering',
    role: 'Cloud Security Specialist',
    status: 'Inactive',
    joining_date: '2021-03-29',
    salary: '$130,000',
    blood_group: 'O-',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    manager_name: 'Marcus Vance',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Austin Tech Center',
    employment_type: 'Full-Time',
    experience: '8 Years',
    emergency_contact: '+1 (555) 012-8833 (Spouse)',
    dob: '1990-12-05',
    gender: 'Male',
    skills: 'Penetration Testing, IAM, ISO27001, AWS Security',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-9902',
    bank_account_last4: 'ACC-****-4477',
  },
  {
    id: 21,
    employee_id: 'EMP-1021',
    name: 'Isabella Green',
    email: 'isabella.g@company.com',
    phone: '+1 (555) 123-7890',
    department: 'Product',
    role: 'Associate Product Manager',
    status: 'Active',
    joining_date: '2023-07-01',
    salary: '$90,000',
    blood_group: 'AB+',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    manager_name: 'Jessica Wilson',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '2 Years',
    emergency_contact: '+1 (555) 123-5544 (Parent)',
    dob: '1998-04-12',
    gender: 'Female',
    skills: 'User Stories, Backlog Grooming, Jira, Analytics',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-2290',
    bank_account_last4: 'ACC-****-8810',
  },
  {
    id: 22,
    employee_id: 'EMP-1022',
    name: 'William Baker',
    email: 'william.b@company.com',
    phone: '+1 (555) 234-8902',
    department: 'Finance',
    role: 'Payroll Administrator',
    status: 'Active',
    joining_date: '2022-04-14',
    salary: '$76,000',
    blood_group: 'A-',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    manager_name: 'Ethan White',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '4 Years',
    emergency_contact: '+1 (555) 234-7711 (Spouse)',
    dob: '1995-09-29',
    gender: 'Male',
    skills: 'ADP, Direct Deposit, Tax Withholding, Compliance',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-3388',
    bank_account_last4: 'ACC-****-9902',
  },
  {
    id: 23,
    employee_id: 'EMP-1023',
    name: 'Sophia Adams',
    email: 'sophia.a@company.com',
    phone: '+1 (555) 345-9013',
    department: 'Marketing',
    role: 'Social Media Manager',
    status: 'Active',
    joining_date: '2022-12-05',
    salary: '$78,000',
    blood_group: 'B+',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    manager_name: 'Sophia Williams',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Remote (California)',
    employment_type: 'Full-Time',
    experience: '4 Years',
    emergency_contact: '+1 (555) 345-6677 (Spouse)',
    dob: '1995-03-03',
    gender: 'Female',
    skills: 'Instagram Strategy, TikTok, Influencer Marketing, Video Editing',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-6670',
    bank_account_last4: 'ACC-****-1144',
  },
  {
    id: 24,
    employee_id: 'EMP-1024',
    name: 'James Nelson',
    email: 'james.n@company.com',
    phone: '+1 (555) 456-0124',
    department: 'Sales',
    role: 'Senior Account Executive',
    status: 'Active',
    joining_date: '2021-02-18',
    salary: '$105,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    manager_name: 'Olivia Harris',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '6 Years',
    emergency_contact: '+1 (555) 456-2288 (Spouse)',
    dob: '1992-11-20',
    gender: 'Male',
    skills: 'HubSpot, Sales Pitch, Client Retention, Deal Closing',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-8840',
    bank_account_last4: 'ACC-****-5522',
  },
  {
    id: 25,
    employee_id: 'EMP-1025',
    name: 'Charlotte Carter',
    email: 'charlotte.c@company.com',
    phone: '+1 (555) 567-1235',
    department: 'Engineering',
    role: 'Mobile App Developer',
    status: 'Active',
    joining_date: '2022-10-24',
    salary: '$112,000',
    blood_group: 'A+',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    manager_name: 'Alex Morgan',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Austin Tech Center',
    employment_type: 'Full-Time',
    experience: '5 Years',
    emergency_contact: '+1 (555) 567-9911 (Parent)',
    dob: '1994-07-08',
    gender: 'Female',
    skills: 'React Native, Swift, Kotlin, App Store Deployment',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1149',
    bank_account_last4: 'ACC-****-3390',
  },
  {
    id: 26,
    employee_id: 'EMP-1026',
    name: 'Henry Mitchell',
    email: 'henry.m@company.com',
    phone: '+1 (555) 678-2346',
    department: 'Engineering',
    role: 'Data Engineer',
    status: 'On Leave',
    joining_date: '2021-09-01',
    salary: '$118,000',
    blood_group: 'B-',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    manager_name: 'Marcus Vance',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Seattle Tech Hub',
    employment_type: 'Full-Time',
    experience: '6 Years',
    emergency_contact: '+1 (555) 678-0022 (Spouse)',
    dob: '1992-05-15',
    gender: 'Male',
    skills: 'Python, Spark, Snowflake, Airflow, SQL',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-5501',
    bank_account_last4: 'ACC-****-7711',
  },
  {
    id: 27,
    employee_id: 'EMP-1027',
    name: 'Amelia Perez',
    email: 'amelia.p@company.com',
    phone: '+1 (555) 789-3457',
    department: 'Product',
    role: 'Product Researcher',
    status: 'Active',
    joining_date: '2023-01-20',
    salary: '$86,000',
    blood_group: 'O-',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    manager_name: 'David Chen',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '3 Years',
    emergency_contact: '+1 (555) 789-4400 (Spouse)',
    dob: '1996-08-01',
    gender: 'Female',
    skills: 'User Interviews, Usability Testing, Quantitative Data',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-7740',
    bank_account_last4: 'ACC-****-2289',
  },
  {
    id: 28,
    employee_id: 'EMP-1028',
    name: 'Lucas Roberts',
    email: 'lucas.r@company.com',
    phone: '+1 (555) 890-4568',
    department: 'Human Resources',
    role: 'HR Assistant',
    status: 'Active',
    joining_date: '2023-06-15',
    salary: '$62,000',
    blood_group: 'AB+',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    manager_name: 'Elena Rostova',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '1 Year',
    emergency_contact: '+1 (555) 890-7799 (Parent)',
    dob: '1999-10-10',
    gender: 'Male',
    skills: 'Onboarding, Workday, Employee Records',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-9941',
    bank_account_last4: 'ACC-****-1100',
  },
  {
    id: 29,
    employee_id: 'EMP-1029',
    name: 'Harper Turner',
    email: 'harper.t@company.com',
    phone: '+1 (555) 901-5679',
    department: 'Finance',
    role: 'Financial Controller',
    status: 'Active',
    joining_date: '2019-08-12',
    salary: '$145,000',
    blood_group: 'A+',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '11 Years',
    emergency_contact: '+1 (555) 901-8822 (Spouse)',
    dob: '1987-12-30',
    gender: 'Female',
    skills: 'Financial Risk, Corporate Audit, SEC Reporting, Treasury',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-3310',
    bank_account_last4: 'ACC-****-6644',
  },
  {
    id: 30,
    employee_id: 'EMP-1030',
    name: 'Jack Phillips',
    email: 'jack.p@company.com',
    phone: '+1 (555) 012-6790',
    department: 'Marketing',
    role: 'Brand Manager',
    status: 'Inactive',
    joining_date: '2020-12-01',
    salary: '$98,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    manager_name: 'Sophia Williams',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '6 Years',
    emergency_contact: '+1 (555) 012-4411 (Spouse)',
    dob: '1992-04-05',
    gender: 'Male',
    skills: 'Brand Identity, Campaigns, PR, Event Management',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-6629',
    bank_account_last4: 'ACC-****-8833',
  },
  {
    id: 31,
    employee_id: 'EMP-1031',
    name: 'Oliver Queen',
    email: 'oliver.queen@company.com',
    phone: '+1 (555) 123-0031',
    department: 'Engineering',
    role: 'Cyber Security Lead',
    status: 'Active',
    joining_date: '2021-04-10',
    salary: '$135,000',
    blood_group: 'AB+',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    manager_name: 'Alex Morgan',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '8 Years',
    emergency_contact: '+1 (555) 999-0031 (Sister)',
    dob: '1990-08-15',
    gender: 'Male',
    skills: 'Penetration Testing, CISSP, OAuth, Firewalls, AWS Security',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1131',
    bank_account_last4: 'ACC-****-9931',
  },
  {
    id: 32,
    employee_id: 'EMP-1032',
    name: 'Penelope Feathering',
    email: 'penelope.f@company.com',
    phone: '+1 (555) 123-0032',
    department: 'HR',
    role: 'Talent Acquisition Manager',
    status: 'Active',
    joining_date: '2022-09-01',
    salary: '$92,000',
    blood_group: 'A-',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    manager_name: 'Emily Watson',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'London Office',
    employment_type: 'Full-Time',
    experience: '5 Years',
    emergency_contact: '+1 (555) 999-0032 (Mother)',
    dob: '1995-11-20',
    gender: 'Female',
    skills: 'Technical Sourcing, LinkedIn Recruiter, Compensation, Onboarding',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1132',
    bank_account_last4: 'ACC-****-9932',
  },
  {
    id: 33,
    employee_id: 'EMP-1033',
    name: 'Quentin Tarantino',
    email: 'quentin.t@company.com',
    phone: '+1 (555) 123-0033',
    department: 'Marketing',
    role: 'Video Content Lead',
    status: 'On Leave',
    joining_date: '2020-01-15',
    salary: '$105,000',
    blood_group: 'B+',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    manager_name: 'Jack Phillips',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '10 Years',
    emergency_contact: '+1 (555) 999-0033 (Brother)',
    dob: '1988-03-27',
    gender: 'Male',
    skills: 'Premiere Pro, Storyboarding, Color Grading, Campaign Strategy',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1133',
    bank_account_last4: 'ACC-****-9933',
  },
  {
    id: 34,
    employee_id: 'EMP-1034',
    name: 'Rachel Green',
    email: 'rachel.green@company.com',
    phone: '+1 (555) 123-0034',
    department: 'Sales',
    role: 'Account Executive',
    status: 'Active',
    joining_date: '2023-02-14',
    salary: '$88,000',
    blood_group: 'O-',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150',
    manager_name: 'Marcus Brody',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '4 Years',
    experience_level: 'Mid Level',
    emergency_contact: '+1 (555) 999-0034 (Father)',
    dob: '1996-05-05',
    gender: 'Female',
    skills: 'B2B Sales, Salesforce, Deal Negotiation, Client Relations',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1134',
    bank_account_last4: 'ACC-****-9934',
  },
  {
    id: 35,
    employee_id: 'EMP-1035',
    name: 'Steven Strange',
    email: 'steven.strange@company.com',
    phone: '+1 (555) 123-0035',
    department: 'Operations',
    role: 'Chief Medical & Wellness Officer',
    status: 'Active',
    joining_date: '2019-11-01',
    salary: '$160,000',
    blood_group: 'A+',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '14 Years',
    emergency_contact: '+1 (555) 999-0035 (Spouse)',
    dob: '1982-11-11',
    gender: 'Male',
    skills: 'Corporate Health, Occupational Safety, Wellness Programs',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1135',
    bank_account_last4: 'ACC-****-9935',
  },
  {
    id: 36,
    employee_id: 'EMP-1036',
    name: 'Tina Fey',
    email: 'tina.fey@company.com',
    phone: '+1 (555) 123-0036',
    department: 'Marketing',
    role: 'Copywriter & Brand Voice Specialist',
    status: 'Active',
    joining_date: '2022-07-15',
    salary: '$82,000',
    blood_group: 'B-',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    manager_name: 'Jack Phillips',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Contract',
    experience: '7 Years',
    emergency_contact: '+1 (555) 999-0036 (Spouse)',
    dob: '1991-05-18',
    gender: 'Female',
    skills: 'Ad Copy, Brand Tone, Content Strategy, SEO Writing',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-1136',
    bank_account_last4: 'ACC-****-9936',
  },
  {
    id: 37,
    employee_id: 'EMP-1037',
    name: 'Ulysses Grant',
    email: 'ulysses.grant@company.com',
    phone: '+1 (555) 123-0037',
    department: 'Finance',
    role: 'Senior Financial Analyst',
    status: 'Inactive',
    joining_date: '2018-05-20',
    salary: '$110,000',
    blood_group: 'AB-',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    manager_name: 'Victoria Beckham',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '9 Years',
    emergency_contact: '+1 (555) 999-0037 (Son)',
    dob: '1986-04-27',
    gender: 'Male',
    skills: 'Financial Modeling, Forecasting, Valuation, Excel PowerPivot',
    performance_rating: 'Needs Improvement',
    tax_id: 'SSN-****-1137',
    bank_account_last4: 'ACC-****-9937',
  },
  {
    id: 38,
    employee_id: 'EMP-1038',
    name: 'Violet Parr',
    email: 'violet.parr@company.com',
    phone: '+1 (555) 123-0038',
    department: 'Engineering',
    role: 'QA Automation Engineer',
    status: 'Active',
    joining_date: '2023-06-01',
    salary: '$95,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    manager_name: 'Alex Morgan',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'London Office',
    employment_type: 'Full-Time',
    experience: '4 Years',
    emergency_contact: '+1 (555) 999-0038 (Mother)',
    dob: '1997-09-12',
    gender: 'Female',
    skills: 'Cypress, Playwright, Selenium, Jest, CI/CD Integration',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1138',
    bank_account_last4: 'ACC-****-9938',
  },
  {
    id: 39,
    employee_id: 'EMP-1039',
    name: 'Walter White',
    email: 'walter.white@company.com',
    phone: '+1 (555) 123-0039',
    department: 'Product',
    role: 'Principal Chemical Compliance Specialist',
    status: 'Active',
    joining_date: '2017-08-14',
    salary: '$150,000',
    blood_group: 'A+',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    manager_name: 'David Chen',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '15 Years',
    emergency_contact: '+1 (555) 999-0039 (Wife)',
    dob: '1979-09-07',
    gender: 'Male',
    skills: 'Chemical Safety, OSHA Standards, Quality Assurance, Audits',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1139',
    bank_account_last4: 'ACC-****-9939',
  },
  {
    id: 40,
    employee_id: 'EMP-1040',
    name: 'Xena Warrior',
    email: 'xena.w@company.com',
    phone: '+1 (555) 123-0040',
    department: 'Sales',
    role: 'Global Expansion Specialist',
    status: 'Active',
    joining_date: '2021-10-10',
    salary: '$125,000',
    blood_group: 'B+',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    manager_name: 'Marcus Brody',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '9 Years',
    emergency_contact: '+1 (555) 999-0040 (Partner)',
    dob: '1989-12-04',
    gender: 'Female',
    skills: 'EMEA Expansion, Enterprise Negotiation, Cross-border Sales',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1140',
    bank_account_last4: 'ACC-****-9940',
  },
  {
    id: 41,
    employee_id: 'EMP-1041',
    name: 'Yusuf Pathan',
    email: 'yusuf.p@company.com',
    phone: '+1 (555) 123-0041',
    department: 'Engineering',
    role: 'Database Administrator (DBA)',
    status: 'Active',
    joining_date: '2020-03-01',
    salary: '$118,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    manager_name: 'Alex Morgan',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '8 Years',
    emergency_contact: '+1 (555) 999-0041 (Brother)',
    dob: '1991-07-22',
    gender: 'Male',
    skills: 'PostgreSQL, MySQL Tuning, Redis, MongoDB, Data Replication',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1141',
    bank_account_last4: 'ACC-****-9941',
  },
  {
    id: 42,
    employee_id: 'EMP-1042',
    name: 'Zendaya Coleman',
    email: 'zendaya.c@company.com',
    phone: '+1 (555) 123-0042',
    department: 'Product',
    role: 'UI/UX Visual Designer',
    status: 'Active',
    joining_date: '2023-01-10',
    salary: '$96,000',
    blood_group: 'A-',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    manager_name: 'David Chen',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'London Office',
    employment_type: 'Full-Time',
    experience: '5 Years',
    emergency_contact: '+1 (555) 999-0042 (Sister)',
    dob: '1996-09-01',
    gender: 'Female',
    skills: 'Figma Design Systems, Micro-interactions, Motion Design, Prototyping',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1142',
    bank_account_last4: 'ACC-****-9942',
  },
  {
    id: 43,
    employee_id: 'EMP-1043',
    name: 'Arthur Pendelton',
    email: 'arthur.p@company.com',
    phone: '+1 (555) 123-0043',
    department: 'Legal',
    role: 'Corporate Legal Counsel',
    status: 'Active',
    joining_date: '2019-06-15',
    salary: '$155,000',
    blood_group: 'B+',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '12 Years',
    emergency_contact: '+1 (555) 999-0043 (Spouse)',
    dob: '1984-02-14',
    gender: 'Male',
    skills: 'IP Protection, Contracts, GDPR Compliance, Mergers & Acquisitions',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1143',
    bank_account_last4: 'ACC-****-9943',
  },
  {
    id: 44,
    employee_id: 'EMP-1044',
    name: 'Barbara Gordon',
    email: 'barbara.g@company.com',
    phone: '+1 (555) 123-0044',
    department: 'Engineering',
    role: 'Information Architect',
    status: 'Active',
    joining_date: '2021-11-20',
    salary: '$122,000',
    blood_group: 'O-',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    manager_name: 'Alex Morgan',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '7 Years',
    emergency_contact: '+1 (555) 999-0044 (Father)',
    dob: '1992-10-15',
    gender: 'Female',
    skills: 'Data Architecture, Knowledge Graphs, Search indexing, Elasticsearch',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1144',
    bank_account_last4: 'ACC-****-9944',
  },
  {
    id: 45,
    employee_id: 'EMP-1045',
    name: 'Charles Xavier',
    email: 'charles.x@company.com',
    phone: '+1 (555) 123-0045',
    department: 'HR',
    role: 'Director of Learning & Development',
    status: 'Active',
    joining_date: '2017-01-10',
    salary: '$140,000',
    blood_group: 'AB+',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    manager_name: 'Emily Watson',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '16 Years',
    emergency_contact: '+1 (555) 999-0045 (Sister)',
    dob: '1978-07-13',
    gender: 'Male',
    skills: 'Leadership Development, Executive Coaching, LMS, Curriculum',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1145',
    bank_account_last4: 'ACC-****-9945',
  },
  {
    id: 46,
    employee_id: 'EMP-1046',
    name: 'Diana Prince',
    email: 'diana.prince@company.com',
    phone: '+1 (555) 123-0046',
    department: 'Operations',
    role: 'Director of Global Facilities',
    status: 'Active',
    joining_date: '2020-05-18',
    salary: '$138,000',
    blood_group: 'A+',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'London Office',
    employment_type: 'Full-Time',
    experience: '10 Years',
    emergency_contact: '+1 (555) 999-0046 (Mother)',
    dob: '1988-03-22',
    gender: 'Female',
    skills: 'Facility Management, Real Estate Contracts, Environmental Sustainability',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1146',
    bank_account_last4: 'ACC-****-9946',
  },
  {
    id: 47,
    employee_id: 'EMP-1047',
    name: 'Edward Elric',
    email: 'edward.e@company.com',
    phone: '+1 (555) 123-0047',
    department: 'Engineering',
    role: 'Embedded Systems Engineer',
    status: 'Active',
    joining_date: '2022-08-01',
    salary: '$108,000',
    blood_group: 'B-',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    manager_name: 'Alex Morgan',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '6 Years',
    emergency_contact: '+1 (555) 999-0047 (Brother)',
    dob: '1994-01-30',
    gender: 'Male',
    skills: 'C++, Rust, RTOS, Hardware Prototyping, IoT Architecture',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1147',
    bank_account_last4: 'ACC-****-9947',
  },
  {
    id: 48,
    employee_id: 'EMP-1048',
    name: 'Fiona Gallagher',
    email: 'fiona.g@company.com',
    phone: '+1 (555) 123-0048',
    department: 'Finance',
    role: 'Payroll & Benefits Administrator',
    status: 'On Leave',
    joining_date: '2021-03-12',
    salary: '$84,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150',
    manager_name: 'Victoria Beckham',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '5 Years',
    emergency_contact: '+1 (555) 999-0048 (Brother)',
    dob: '1995-06-14',
    gender: 'Female',
    skills: 'ADP Payroll, Workday, 401(k) Compliance, Tax Filings',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-1148',
    bank_account_last4: 'ACC-****-9948',
  },
  {
    id: 49,
    employee_id: 'EMP-1049',
    name: 'Gareth Bale',
    email: 'gareth.b@company.com',
    phone: '+1 (555) 123-0049',
    department: 'Sales',
    role: 'Regional Sales Manager (LATAM)',
    status: 'Active',
    joining_date: '2020-09-01',
    salary: '$115,000',
    blood_group: 'A-',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    manager_name: 'Marcus Brody',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '8 Years',
    emergency_contact: '+1 (555) 999-0049 (Wife)',
    dob: '1991-07-16',
    gender: 'Male',
    skills: 'LATAM Enterprise Sales, Spanish & Portuguese Fluency, CRM',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1149',
    bank_account_last4: 'ACC-****-9949',
  },
  {
    id: 50,
    employee_id: 'EMP-1050',
    name: 'Hannah Abbott',
    email: 'hannah.a@company.com',
    phone: '+1 (555) 123-0050',
    department: 'Customer Support',
    role: 'Tier 3 Enterprise Support Lead',
    status: 'Active',
    joining_date: '2022-04-18',
    salary: '$86,000',
    blood_group: 'AB-',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    manager_name: 'Kevin Bacon',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'London Office',
    employment_type: 'Full-Time',
    experience: '4 Years',
    emergency_contact: '+1 (555) 999-0050 (Father)',
    dob: '1997-12-01',
    gender: 'Female',
    skills: 'Zendesk Master, API Troubleshooting, Escalation Management',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1150',
    bank_account_last4: 'ACC-****-9950',
  },
  {
    id: 51,
    employee_id: 'EMP-1051',
    name: 'Ian Malcolm',
    email: 'ian.m@company.com',
    phone: '+1 (555) 123-0051',
    department: 'Engineering',
    role: 'Chaos Engineering Specialist',
    status: 'Active',
    joining_date: '2019-10-15',
    salary: '$142,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    manager_name: 'Alex Morgan',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '11 Years',
    emergency_contact: '+1 (555) 999-0051 (Wife)',
    dob: '1985-06-25',
    gender: 'Male',
    skills: 'Gremlin, Resilience Testing, Distributed Systems, Failover Testing',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1151',
    bank_account_last4: 'ACC-****-9951',
  },
  {
    id: 52,
    employee_id: 'EMP-1052',
    name: 'Jessica Jones',
    email: 'jessica.j@company.com',
    phone: '+1 (555) 123-0052',
    department: 'Operations',
    role: 'Corporate Security Lead',
    status: 'Active',
    joining_date: '2021-02-10',
    salary: '$112,000',
    blood_group: 'B+',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '7 Years',
    emergency_contact: '+1 (555) 999-0052 (Friend)',
    dob: '1993-02-28',
    gender: 'Female',
    skills: 'Risk Mitigation, Surveillance, Background Screenings, Crisis Response',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1152',
    bank_account_last4: 'ACC-****-9952',
  },
  {
    id: 53,
    employee_id: 'EMP-1053',
    name: 'Kyle Reese',
    email: 'kyle.reese@company.com',
    phone: '+1 (555) 123-0053',
    department: 'Engineering',
    role: 'Infrastructure Automation Architect',
    status: 'Inactive',
    joining_date: '2018-09-01',
    salary: '$136,000',
    blood_group: 'A-',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    manager_name: 'Alex Morgan',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '10 Years',
    emergency_contact: '+1 (555) 999-0053 (Spouse)',
    dob: '1987-08-11',
    gender: 'Male',
    skills: 'Terraform, Ansible, AWS CloudFormation, Bash Scripting',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-1153',
    bank_account_last4: 'ACC-****-9953',
  },
  {
    id: 54,
    employee_id: 'EMP-1054',
    name: 'Lara Croft',
    email: 'lara.croft@company.com',
    phone: '+1 (555) 123-0054',
    department: 'Product',
    role: 'Lead User Researcher',
    status: 'Active',
    joining_date: '2022-01-20',
    salary: '$118,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    manager_name: 'David Chen',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'London Office',
    employment_type: 'Full-Time',
    experience: '8 Years',
    emergency_contact: '+1 (555) 999-0054 (Butler)',
    dob: '1991-02-14',
    gender: 'Female',
    skills: 'Usability Testing, Ethnographic Research, Quantitative Surveys',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1154',
    bank_account_last4: 'ACC-****-9954',
  },
  {
    id: 55,
    employee_id: 'EMP-1055',
    name: 'Michael Scott',
    email: 'michael.scott@company.com',
    phone: '+1 (555) 123-0055',
    department: 'Sales',
    role: 'Regional Branch Director',
    status: 'Active',
    joining_date: '2016-04-01',
    salary: '$148,000',
    blood_group: 'AB+',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    manager_name: 'Marcus Brody',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '18 Years',
    emergency_contact: '+1 (555) 999-0055 (Wife)',
    dob: '1976-03-15',
    gender: 'Male',
    skills: 'Client Management, Team Motivation, Negotiations, Regional Sales',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1155',
    bank_account_last4: 'ACC-****-9955',
  },
  {
    id: 56,
    employee_id: 'EMP-1056',
    name: 'Nancy Drew',
    email: 'nancy.drew@company.com',
    phone: '+1 (555) 123-0056',
    department: 'Legal',
    role: 'Internal Fraud Investigator',
    status: 'Active',
    joining_date: '2023-03-01',
    salary: '$94,000',
    blood_group: 'A+',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    manager_name: 'Arthur Pendelton',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '4 Years',
    emergency_contact: '+1 (555) 999-0056 (Father)',
    dob: '1997-04-20',
    gender: 'Female',
    skills: 'Forensic Accounting, Digital Forensics, Risk Analysis',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1156',
    bank_account_last4: 'ACC-****-9956',
  },
  {
    id: 57,
    employee_id: 'EMP-1057',
    name: 'Oscar Martinez',
    email: 'oscar.m@company.com',
    phone: '+1 (555) 123-0057',
    department: 'Finance',
    role: 'Senior Accountant',
    status: 'Active',
    joining_date: '2019-07-15',
    salary: '$104,000',
    blood_group: 'B-',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    manager_name: 'Victoria Beckham',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '9 Years',
    emergency_contact: '+1 (555) 999-0057 (Partner)',
    dob: '1989-11-09',
    gender: 'Male',
    skills: 'General Ledger, Financial Auditing, QuickBooks, GAAP',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1157',
    bank_account_last4: 'ACC-****-9957',
  },
  {
    id: 58,
    employee_id: 'EMP-1058',
    name: 'Pam Beesly',
    email: 'pam.b@company.com',
    phone: '+1 (555) 123-0058',
    department: 'HR',
    role: 'Office Experience & Culture Manager',
    status: 'Active',
    joining_date: '2020-02-01',
    salary: '$78,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    manager_name: 'Emily Watson',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '6 Years',
    emergency_contact: '+1 (555) 999-0058 (Husband)',
    dob: '1993-03-25',
    gender: 'Female',
    skills: 'Employee Engagement, Event Planning, Graphic Design, Internal Comms',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-1158',
    bank_account_last4: 'ACC-****-9958',
  },
  {
    id: 59,
    employee_id: 'EMP-1059',
    name: 'Quinn Fabray',
    email: 'quinn.f@company.com',
    phone: '+1 (555) 123-0059',
    department: 'Marketing',
    role: 'Social Media & Influencer Lead',
    status: 'Active',
    joining_date: '2022-11-01',
    salary: '$89,000',
    blood_group: 'A-',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150',
    manager_name: 'Jack Phillips',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'London Office',
    employment_type: 'Full-Time',
    experience: '4 Years',
    emergency_contact: '+1 (555) 999-0059 (Mother)',
    dob: '1996-10-31',
    gender: 'Female',
    skills: 'Instagram Growth, TikTok Ads, Influencer Relations, Virality',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1159',
    bank_account_last4: 'ACC-****-9959',
  },
  {
    id: 60,
    employee_id: 'EMP-1060',
    name: 'Ron Swanson',
    email: 'ron.swanson@company.com',
    phone: '+1 (555) 123-0060',
    department: 'Operations',
    role: 'VP of Procurement & Infrastructure',
    status: 'Active',
    joining_date: '2015-01-05',
    salary: '$175,000',
    blood_group: 'O-',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '22 Years',
    emergency_contact: '+1 (555) 999-0060 (Wife)',
    dob: '1972-06-05',
    gender: 'Male',
    skills: 'Vendor Negotiation, Budget Cutting, Woodworking, Supply Chain',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1160',
    bank_account_last4: 'ACC-****-9960',
  },
  {
    id: 61,
    employee_id: 'EMP-1061',
    name: 'Selina Kyle',
    email: 'selina.k@company.com',
    phone: '+1 (555) 123-0061',
    department: 'Sales',
    role: 'Strategic Partnerships Lead',
    status: 'Active',
    joining_date: '2021-08-15',
    salary: '$128,000',
    blood_group: 'AB-',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    manager_name: 'Marcus Brody',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '8 Years',
    emergency_contact: '+1 (555) 999-0061 (Sister)',
    dob: '1992-11-03',
    gender: 'Female',
    skills: 'Channel Partnerships, Joint Ventures, Co-Marketing, B2B Networking',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1161',
    bank_account_last4: 'ACC-****-9961',
  },
  {
    id: 62,
    employee_id: 'EMP-1062',
    name: 'Ted Lasso',
    email: 'ted.lasso@company.com',
    phone: '+1 (555) 123-0062',
    department: 'HR',
    role: 'Chief Happiness & Retention Officer',
    status: 'Active',
    joining_date: '2020-07-01',
    salary: '$130,000',
    blood_group: 'A+',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    manager_name: 'Emily Watson',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'London Office',
    employment_type: 'Full-Time',
    experience: '14 Years',
    emergency_contact: '+1 (555) 999-0062 (Son)',
    dob: '1981-08-09',
    gender: 'Male',
    skills: 'Culture Building, Conflict Resolution, Optimism Coaching, Team Synergy',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1162',
    bank_account_last4: 'ACC-****-9962',
  },
  {
    id: 63,
    employee_id: 'EMP-1063',
    name: 'Uma Thurman',
    email: 'uma.t@company.com',
    phone: '+1 (555) 123-0063',
    department: 'Engineering',
    role: 'Principal Mobile Architect (iOS/Android)',
    status: 'Active',
    joining_date: '2019-04-12',
    salary: '$152,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    manager_name: 'Alex Morgan',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '12 Years',
    emergency_contact: '+1 (555) 999-0063 (Spouse)',
    dob: '1985-04-29',
    gender: 'Female',
    skills: 'Swift, Kotlin, React Native, Mobile Security, CI/CD Bitrise',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1163',
    bank_account_last4: 'ACC-****-9963',
  },
  {
    id: 64,
    employee_id: 'EMP-1064',
    name: 'Victor Vance',
    email: 'victor.v@company.com',
    phone: '+1 (555) 123-0064',
    department: 'Customer Support',
    role: 'Technical Support Escalations Manager',
    status: 'On Leave',
    joining_date: '2021-06-18',
    salary: '$90,000',
    blood_group: 'B+',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    manager_name: 'Kevin Bacon',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '6 Years',
    emergency_contact: '+1 (555) 999-0064 (Brother)',
    dob: '1993-09-19',
    gender: 'Male',
    skills: 'SLA Monitoring, Critical Incident Mgmt, Jira Service Desk',
    performance_rating: 'Meets Expectations',
    tax_id: 'SSN-****-1164',
    bank_account_last4: 'ACC-****-9964',
  },
  {
    id: 65,
    employee_id: 'EMP-1065',
    name: 'Wanda Maximoff',
    email: 'wanda.m@company.com',
    phone: '+1 (555) 123-0065',
    department: 'Engineering',
    role: 'AI / Machine Learning Engineer',
    status: 'Active',
    joining_date: '2023-01-15',
    salary: '$145,000',
    blood_group: 'AB+',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    manager_name: 'Alex Morgan',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '7 Years',
    emergency_contact: '+1 (555) 999-0065 (Brother)',
    dob: '1994-02-10',
    gender: 'Female',
    skills: 'PyTorch, TensorFlow, LLMs, LangChain, Vector Databases, Python',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1165',
    bank_account_last4: 'ACC-****-9965',
  },
  {
    id: 66,
    employee_id: 'EMP-1066',
    name: 'Xavier Hernandez',
    email: 'xavier.h@company.com',
    phone: '+1 (555) 123-0066',
    department: 'Product',
    role: 'Senior Technical Product Manager',
    status: 'Active',
    joining_date: '2020-11-20',
    salary: '$134,000',
    blood_group: 'A-',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    manager_name: 'David Chen',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'San Francisco Tech Hub',
    employment_type: 'Full-Time',
    experience: '9 Years',
    emergency_contact: '+1 (555) 999-0066 (Wife)',
    dob: '1989-01-25',
    gender: 'Male',
    skills: 'Roadmap Planning, Scrum Master, API Products, Developer Experience',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1166',
    bank_account_last4: 'ACC-****-9966',
  },
  {
    id: 67,
    employee_id: 'EMP-1067',
    name: 'Yennefer Vengerberg',
    email: 'yennefer.v@company.com',
    phone: '+1 (555) 123-0067',
    department: 'Marketing',
    role: 'Director of Brand Strategy',
    status: 'Active',
    joining_date: '2018-10-01',
    salary: '$158,000',
    blood_group: 'O-',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    manager_name: 'Jack Phillips',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'London Office',
    employment_type: 'Full-Time',
    experience: '13 Years',
    emergency_contact: '+1 (555) 999-0067 (Partner)',
    dob: '1986-05-19',
    gender: 'Female',
    skills: 'Global Brand Identity, Product Marketing, PR Strategy, Corporate Comms',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1167',
    bank_account_last4: 'ACC-****-9967',
  },
  {
    id: 68,
    employee_id: 'EMP-1068',
    name: 'Zachary Levi',
    email: 'zachary.l@company.com',
    phone: '+1 (555) 123-0068',
    department: 'Sales',
    role: 'Enterprise Solutions Engineer',
    status: 'Active',
    joining_date: '2022-05-10',
    salary: '$120,000',
    blood_group: 'B-',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    manager_name: 'Marcus Brody',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'Chicago Hub',
    employment_type: 'Full-Time',
    experience: '6 Years',
    emergency_contact: '+1 (555) 999-0068 (Wife)',
    dob: '1993-09-29',
    gender: 'Male',
    skills: 'Pre-Sales Demos, Technical RFP Solutions, Solution Architecture',
    performance_rating: 'Exceeds Expectations',
    tax_id: 'SSN-****-1168',
    bank_account_last4: 'ACC-****-9968',
  },
  {
    id: 69,
    employee_id: 'EMP-1069',
    name: 'Amy Santiago',
    email: 'amy.s@company.com',
    phone: '+1 (555) 123-0069',
    department: 'Operations',
    role: 'Director of Process Optimization',
    status: 'Active',
    joining_date: '2019-02-15',
    salary: '$140,000',
    blood_group: 'A+',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150',
    manager_name: 'Sarah Jenkins',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '10 Years',
    emergency_contact: '+1 (555) 999-0069 (Husband)',
    dob: '1989-08-07',
    gender: 'Female',
    skills: 'Six Sigma Black Belt, Process Auditing, Efficiency KPIs, ERP',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1169',
    bank_account_last4: 'ACC-****-9969',
  },
  {
    id: 70,
    employee_id: 'EMP-1070',
    name: 'Jake Peralta',
    email: 'jake.p@company.com',
    phone: '+1 (555) 123-0070',
    department: 'Engineering',
    role: 'Principal Incident Response Lead',
    status: 'Active',
    joining_date: '2018-11-01',
    salary: '$146,000',
    blood_group: 'O+',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    manager_name: 'Alex Morgan',
    createdBy: 'Admin User',
    updatedBy: 'Admin User',
    location: 'New York HQ',
    employment_type: 'Full-Time',
    experience: '11 Years',
    emergency_contact: '+1 (555) 999-0070 (Wife)',
    dob: '1988-06-19',
    gender: 'Male',
    skills: 'Incident Management, Forensic Investigation, Root Cause Analysis, On-Call',
    performance_rating: 'Top Performer',
    tax_id: 'SSN-****-1170',
    bank_account_last4: 'ACC-****-9970',
  }
];
